#! /bin/bash

echo -e '// This file was generated by generate_SystemErrors.sh. Do not edit.\n' > SystemErrors.h
echo | gcc -c - -include /usr/include/errno.h -E -dMM | grep '#define E' |\
  sed -e 's/^#define[[:space:]]*\([^[:space:]]*\)[[:space:]].*/  SE_\1 = \1,/' |\
  sort -u | gcc -c - -include /usr/include/errno.h -E -P | grep '^  SE_' |\
  sed -r -e 's/(.*) = ([0-9]*)/\2 : \1 = \2/' | sort -n | sed -e 's/.*://' |\
  sed -r -e 's%(.*) = 129,%//\1 = 129,        // magic_enum has problems with the value 129, see https://github.com/Neargye/magic_enum/issues/136.%' >> SystemErrors.h
